### ISSUE TITLE
Plugin Idea: (Google) Font Optimization

### ISSUE THREAD

**Issue by kevmodrome** [Elderjs/plugins#23]
Not sure if this is the correct place, feel free to move and/or remove it.

Yesterday I had to do some work on optimizing fonts for [Svelte Summit](https://sveltesummit.com) and realized this is one of those places where an automatic tool is probably very nice to have in order to speed up initial setup of a project. 

Most often I use Google Fonts and sometimes they are HUGE, payload wise. It would be cool to have a plugin that takes an array of fonts (or all fonts in some folder like the image plugin) fetches the correct subset and uses that instead of the font file containing all glyphs.

I'm imagining something like this config:
```js
'@elderjs/plugin-fonts': {
        folders: [
            {
                src: '/fonts/*'
            },
        ],
        options: {
            subset: 'latin',
        }
    }
```

or in the case of font names:

```js
'@elderjs/plugin-fonts': {
        fonts: [
            ['Roboto', 'latin'],
            ['Overpass', 'latin'],
        ]
    }
```

I'll take a look at the image plugin and see if I can get this set up some how.

One major limitation of this is that it might be limited to just Google Fonts. Not sure how this could be solved for local fonts. The fonts in the folder

**Comment by kevmodrome** [comment]
Another thought, you could even set up font matching automatically with hardcoded fallback fonts and `font-display: swap` to avoid jerky text flow issues.

**Comment by nickreese** [comment]
@kevmodrome Love the idea. Would be happy to code review or outline a plugin flow if you or someone wants to develop it. 

A related idea I’ve seen but done at the CDN level to prevent another origin lookup: https://github.com/cloudflare/worker-examples/tree/master/examples/fast-google-fonts

**Comment by kevmodrome** [comment]
Great! This is the API I have landed in:

The idea of the plugin is to fetch the subsets and weights you want automatically, generate the correct  `@font-face` definitions and set up css vars to make using it very easy.So something like:
```js
'@elderjs/plugin-fonts': {
  fonts: [
    {
      name: 'Anton',
      subsets: ['latin'],
      weights: [400, 700],
    }
  ]
}
```
would generate:
```css
@font-face {
  font-family: 'Anton';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: local('Anton Regular'), local('Anton-Regular'),
       url('./fonts/Anton-400-latin.woff') format('woff')
}
@font-face {
  font-family: 'Anton';
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: local('Anton-Bold'), local('Anton-Bold'),
       url('./fonts/Anton-700-latin.woff') format('woff')
}
:root {
  --anton: 'Anton', Impact, sans-serif;
}
```

You then only have to do `font-family: var(--anton)` to automatically get the fallback and font-swapping features. I might omit the fallback and swapping features for now since I would have to add all those manually and that feels like a chore at the moment 😆

**Comment by nickreese** [comment]
@kevmodrome looks like a good plan. Could you take the font name defined in the array and “skewer case” it for the root definitions?

**Comment by kevmodrome** [comment]
Skewer case, that's a new one, haha! I think that should be fine, another thought I had was to use the font short hand property, that way you could define normal/bold vars like so:
```css
:root {
   font-size: 16px // this would be set manually I think?
   --anton-400: 1em 'Anton', Impact, sans-serif;
   --anton-700: bold 1em 'Anton', Impact, sans-serif;
}

p {
   font: var(--anton-400);
}

h1 {
   font: var(--anton-700);
   font-size: 1.2em;
}
```

I'm not sure if I like this though. It's almost as much work as just doing:

```css
h1 {
   font-family: var(--anton);
   font-weight: 700;
   font-size: 1.2em;
}
```

Another option is to set font sizes in the config file but that feels like it could get complex. Better to just focus on the main feature of getting the font files and doing the swapping correctly.
